Repository richarddushime/Implementing-Facial-Recognition-and-Biometric-Attendance-Monitoring-in-Educational-and-Corporate-Set, pull requests merged in 2023-10, with the labels that each got.

#23 Regp
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/settings.cpython-310.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/wsgi.cpython-310.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/settings.py
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/urls.py
  FRB_Attendance_Monitoring/accounts/models.py
  FRB_Attendance_Monitoring/accounts/templates/account_register.html
  FRB_Attendance_Monitoring/accounts/templates/base.html
  FRB_Attendance_Monitoring/accounts/templates/login.html
  FRB_Attendance_Monitoring/accounts/views.py
  FRB_Attendance_Monitoring/linu_ubuntu_requirements.txt
  FRB_Attendance_Monitoring/staff/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/admin.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/apps.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/models.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/views.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/migrations/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/admin.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/apps.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/models.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/views.cpython-310.pyc
  FRB_Attendance_Monitoring/students/forms.py
  FRB_Attendance_Monitoring/students/migrations/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/students/templates/home.html
Labels: enhancement, Ready for review, HACKTOBERFEST-ACCEPTED

#30 Update Code-of-conduct.md
  Code-of-conduct.md
Labels: HACKTOBERFEST-ACCEPTED

#32 Templates
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: documentation, Complete, HACKTOBERFEST-ACCEPTED

#33 Admin Pannel UI
  FRB_Attendance_Monitoring/staff/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/views.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/templates/base.html
  FRB_Attendance_Monitoring/staff/templates/home.html
  FRB_Attendance_Monitoring/staff/templates/index.html
  FRB_Attendance_Monitoring/staff/templates/staff_dashboard.html
  FRB_Attendance_Monitoring/staff/urls.py
  FRB_Attendance_Monitoring/staff/views.py
  FRB_Attendance_Monitoring/static/images/addphotos.png
  FRB_Attendance_Monitoring/static/images/atte.png
  FRB_Attendance_Monitoring/static/images/bg_image.png
  FRB_Attendance_Monitoring/static/images/bga.jpg
  FRB_Attendance_Monitoring/static/images/dashboard.jpg
  FRB_Attendance_Monitoring/static/images/enter.png
  FRB_Attendance_Monitoring/static/images/logo.png
  FRB_Attendance_Monitoring/static/images/register.png
  FRB_Attendance_Monitoring/static/images/reports.png
  FRB_Attendance_Monitoring/static/images/reports2.jpeg
  FRB_Attendance_Monitoring/static/images/train.jpeg
  FRB_Attendance_Monitoring/static/images/training_visualisation.png
  FRB_Attendance_Monitoring/staticfiles/images/addphotos.png
  FRB_Attendance_Monitoring/staticfiles/images/atte.png
  FRB_Attendance_Monitoring/staticfiles/images/bg_image.png
  FRB_Attendance_Monitoring/staticfiles/images/bga.jpg
  FRB_Attendance_Monitoring/staticfiles/images/dashboard.jpg
  FRB_Attendance_Monitoring/staticfiles/images/enter.png
  FRB_Attendance_Monitoring/staticfiles/images/register.png
  FRB_Attendance_Monitoring/staticfiles/images/reports.png
  FRB_Attendance_Monitoring/staticfiles/images/reports2.jpeg
  FRB_Attendance_Monitoring/staticfiles/images/train.jpeg
  FRB_Attendance_Monitoring/staticfiles/images/training_visualisation.png
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#27 Added pre commit hooks
  .pre-commit-config.yaml
Labels: enhancement, help wanted, HACKTOBERFEST-ACCEPTED

#42 Update command.txt
  FRB_Attendance_Monitoring/command.txt
Labels: good first issue, Complete, HACKTOBERFEST-ACCEPTED

#43 Create manage.py doc
  FRB_Attendance_Monitoring/manage.py doc
Labels: documentation, HACKTOBERFEST-ACCEPTED

#44 Update admin.py with CustomUser Model
  FRB_Attendance_Monitoring/accounts/admin.py
Labels: good first issue, HACKTOBERFEST-ACCEPTED

#45 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: Ready for review, Complete, HACKTOBERFEST-ACCEPTED

#47 Layouts files
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/__init__.cpython-311.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/settings.cpython-311.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/urls.cpython-311.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/wsgi.cpython-311.pyc
  FRB_Attendance_Monitoring/layouts/footer.html
  FRB_Attendance_Monitoring/layouts/header.html
  FRB_Attendance_Monitoring/staff/__pycache__/__init__.cpython-311.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/admin.cpython-311.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/apps.cpython-311.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/models.cpython-311.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/urls.cpython-311.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/views.cpython-311.pyc
  FRB_Attendance_Monitoring/staff/migrations/__pycache__/__init__.cpython-311.pyc
  FRB_Attendance_Monitoring/staff/templates/base.html
  FRB_Attendance_Monitoring/staff/templates/index.html
  FRB_Attendance_Monitoring/students/__pycache__/__init__.cpython-311.pyc
  FRB_Attendance_Monitoring/students/__pycache__/admin.cpython-311.pyc
  FRB_Attendance_Monitoring/students/__pycache__/apps.cpython-311.pyc
  FRB_Attendance_Monitoring/students/__pycache__/models.cpython-311.pyc
  FRB_Attendance_Monitoring/students/__pycache__/urls.cpython-311.pyc
  FRB_Attendance_Monitoring/students/__pycache__/views.cpython-311.pyc
  FRB_Attendance_Monitoring/students/migrations/__pycache__/__init__.cpython-311.pyc
Labels: Ready for review, Complete, HACKTOBERFEST-ACCEPTED

#51 admin contact page
  FRB_Attendance_Monitoring/staff/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/views.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/templates/contact.html
  FRB_Attendance_Monitoring/staff/templates/index.html
  FRB_Attendance_Monitoring/staff/urls.py
  FRB_Attendance_Monitoring/staff/views.py
Labels: enhancement, Ready for review, HACKTOBERFEST-ACCEPTED

#53 Normal users landing page || Students
  FRB_Attendance_Monitoring/students/templates/student_dashboard.html
  FRB_Attendance_Monitoring/students/urls.py
  FRB_Attendance_Monitoring/students/views.py
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#56 Staff App Unit tests
  FRB_Attendance_Monitoring/staff/tests.py
Labels: good first issue, HACKTOBERFEST-ACCEPTED

#54 Students Application Unit Tests
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/settings.cpython-310.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/FRB_Attendance_Monitoring/__pycache__/wsgi.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/admin.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/apps.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/models.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/__pycache__/views.cpython-310.pyc
  FRB_Attendance_Monitoring/staff/migrations/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/admin.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/apps.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/models.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/urls.cpython-310.pyc
  FRB_Attendance_Monitoring/students/__pycache__/views.cpython-310.pyc
  FRB_Attendance_Monitoring/students/migrations/__pycache__/__init__.cpython-310.pyc
  FRB_Attendance_Monitoring/students/tests.py
  FRB_Attendance_Monitoring/students/urls.py
  FRB_Attendance_Monitoring/students/views.py
Labels: good first issue, Complete, HACKTOBERFEST-ACCEPTED

#61 New UI Register Page
  FRB_Attendance_Monitoring/accounts/migrations/0001_initial.py
  FRB_Attendance_Monitoring/accounts/templates/account_register.html
Labels: Ready for review, Complete, HACKTOBERFEST-ACCEPTED

#62 Unit Tests for Account Application
  FRB_Attendance_Monitoring/accounts/tests.py
Labels: enhancement, Ready for review, Complete, HACKTOBERFEST-ACCEPTED
